CREATE DATABASE collage;
USE collage;

CREATE TABLE student(
rollno INT PRIMARY KEY,
name VARCHAR(100)
);

SELECT*FROM student;

CREATE TABLE  temp1(
id INT UNIQUE
);

INSERT INTO temp1 VALUES(103);
INSERT INTO temp1 VALUES(106);
INSERT INTO temp1 VALUES(107);
SELECT*FROM temp1;
